### PR TITLE
Reset identity iteration

### LINKED ISSUE #3329: Reset identity iteration
Several tasks to handle:

- [x] Ensure that wording "reset your encryption" is changed to "reset your identity"

Now that the application support resetting the identity:
- [x] Remove the button `Lost your recovery key?` in this screen:
image

- [x] Remove this screen (which was displayed by the button `Lost your recovery key?`
image

- [x] change the wording "Confirm that it's you" to "Confirm your identity"

image

- [x] Add back the banner to tell user to set up their recovery. Done in #3360

image

- [x] Add the sign out option to unblock the user who cannot verify and does not want to reset their identity (waiting for final design) Done in #3359

### Reset legacy:
- [x] Move the confirmation dialog, which was displayed here: **EDIT: We do not change this**
image

on the enter password dialog:

image

[Figma](https://www.figma.com/design/pDlJZGBsri47FNTXMnEdXB/Compound-Android-Templates?node-id=343-14436) 

### Reset OIDC

- [x] Add a confirmation screen: **EDIT: We do not add this screen**

image

[Figma](https://www.figma.com/design/pDlJZGBsri47FNTXMnEdXB/Compound-Android-Templates?node-id=343-14049)

CC @pmaier1

### PR DESCRIPTION
**Pull request by bmarty**
## Content

Handle items in #3329

## Motivation and context

Closes #3329

## Tests

- Reset your identity using Oidc account or password account.

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s):

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 23
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request title will be used in the release note, it clearly define what will change for the user
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR

### CODE REVIEW

**Review by jmartinesp — APPROVED** [review]
LGTM, thanks!

**Comment by jmartinesp** [comment]
Actually, I just re-tested this with OIDC and I find this flow quite weird:

[Screen_recording_20240823_093616.webm](https://github.com/user-attachments/assets/513099da-91bf-4a95-a1d7-83a8970380ae)

I think the new screen should be before the confirmation one with the list of items and the red buttons, right? In fact, that 2nd screen shouldn't be displayed for OIDC *once the website emulates it*, so it makes sense that's the last one before the actual reset.

**Review by jmartinesp — CHANGES_REQUESTED** [review]
I think we should handle the issues mentioned above.

**Comment by bmarty** [comment]
Note to myself: one task added to the issue:  change the wording "Confirm that it's you" to "Confirm your identity"

**Pull request closed without merging**
