### PR TITLE
Upgrade the used JDK in the project to v21

### PR DESCRIPTION
**Pull request by jmartinesp**
## Content

Changes the Gradle config to use JDK 21, and change it in the CI flows too.

## Motivation and context

JDK 21 is the new default in Android Studio Ladybug.

## Tests

Let's see how the CI behaves.

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 23
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request title will be used in the release note, it clearly define what will change for the user
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR

### CODE REVIEW

**Comment by bmarty** [comment]
Note: I have created #3585 to unblock develop, and partially cherry-picked 29b61ca4c6ed78515c358284bf0e2120fd556dbd.

**Comment by jmartinesp** [comment]
> Note: I have created #3585 to unblock develop, and partially cherry-picked [29b61ca](https://github.com/element-hq/element-x-android/commit/29b61ca4c6ed78515c358284bf0e2120fd556dbd).

What I don't know is how did tests even pass the CI in the previous PRs.

**Comment by jmartinesp** [comment]
Also, ouch:

image

It seems like we'll lose almost 2% of coverage.

**Comment by jmartinesp** [comment]
It seems like some code, `*Preview` ones mostly, is now taken into account for code coverage. That's odd, the Kover filters may need some tweaks.

**Comment by jmartinesp** [comment]
It seems like https://github.com/element-hq/element-x-android/pull/3582/commits/397745539ccb957dc82627375842a607b433590c fixed the `Preview` code added to coverage issue, which added lots of untested code because their callback functions would never be called. There's still some coverage regression, but it's now `-0.29%`, not `-1.8%`.

**Comment by bmarty** [comment]
> > Note: I have created #3585 to unblock develop, and partially cherry-picked [29b61ca](https://github.com/element-hq/element-x-android/commit/29b61ca4c6ed78515c358284bf0e2120fd556dbd).
> 
> What I don't know is how did tests even pass the CI in the previous PRs.

#3565 has been merged, then #3554 but the latest was based on an old develop branch. Result is a not compiling develop branch. We may want to mitigate this by enabling merge queue, but this was slowing down the process, and so I prefer to keep it that way and fix issues when they happen, which is quite not frequent, so acceptable.

**Review by bmarty — APPROVED** [review]
Thanks. FTR I had to install JDK21 on my computer:
> brew install openjdk@21 
> sudo ln -sfn /opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-21.jdk

I have added 2 cleanup commits, please review!

**Comment by jmartinesp** [comment]
> Thanks. FTR I had to install JDK21 on my computer

Thanks for the tip! This is indeed needed if you aren't using the JDK embedded in AS Ladybug.

Also, thanks for the cleanup!

**Pull request merged**
