### PR TITLE
Enable identity pinning violation notifications unconditionally

### PR DESCRIPTION
**Pull request by andybalaam**
## Content

Enable identity pinning violation notifications unconditionally (remove the feature flag we added when this feature seemed unstable).

## Motivation and context

([Internal issue](https://github.com/element-hq/element-internal/issues/644)). Part of the Trust and Decorations work.

In #3648 we disabled identity change notifications based on a default-off feature flag, because we found some bugs in the feature. The bugs are fixed and we think it's time to enable the feature unconditionally.

## Tests

On a local Synapse, I connected 2 users and changed the identity of one. I verified that, despite not setting any labs flags, the "identity changed" banner appeared.

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s): VanillaIceCream

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 23
- [ ] ~~UI change has been tested on both light and dark themes~~ - no UI change
- [ ] ~~Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility~~ - no UI change
- [x] Pull request is based on the develop branch
- [x] Pull request title will be used in the release note, it clearly define what will change for the user
- [ ] ~~Pull request includes screenshots or videos if containing UI changes~~ - no UI changes
- [ ] ~~Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)~~ - I am exempt because I am an Element employee
- [x] You've made a self review of your PR

### CODE REVIEW

**Comment by andybalaam** [comment]
Test failure looks unrelated, unless I'm missing something?

**Review by bmarty — APPROVED** [review]
Thanks! We have a flaky test, I have re-run the test, it should be fine.

**Comment by andybalaam** [comment]
@bmarty would you like me to rebase before merging?

**Comment by bmarty** [comment]
@andybalaam no, you can merge anytime!

**Pull request merged**
