### PR TITLE
Move attachment preview above the composer, allowing to add captions …

### LINKED ISSUE #2573: Add captions to sent image and video files
#### What would you like to do?

I want to have some UI that allows me to add captions to image or video files I'm about to send.

Now that https://github.com/element-hq/element-x-android/issues/2521 is implemented it is possible to send both a plain text and formatted caption. It would be nice to be able to send at least the plain text version, if not both.

#### Why would you like to do it?

It's weird we can display captions but not send them. It's also present in most other IM apps.

#### How would you like to achieve it?

By implementing some new design that adds a text field to the attachment preview screen displayed before a media attachment is sent.

### Have you considered any alternatives?

We could just leave it as is.

### Additional context

Something similar to WhatsApp's implementation would probably be a nice fit to expand our current UI:

image

### Are you willing to provide a PR?

Yes

### PR DESCRIPTION
**Pull request by surakin**
…to media/attachments

Fixes #2573 

I has too many UX changes for my taste so if one of the team likes it and wants to pick it up that's fine by me :)

 
## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Technical
- [ ] Other :

## Screenshots / GIFs
Before sending
image
After sending
image

## Tests

- Step 1
- Step 2
- Step ...

## Tested devices

- [x] Physical
- [x] Emulator
- OS version(s):

## Checklist

- [x] Changes have been tested on an Android device or Android emulator with API 23
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#changelog
- [x] Pull request includes screenshots or videos if containing UI changes
- [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR

### CODE REVIEW

**Comment by frebib** [comment]
Is it necessary to keep the `Sending {spinner}` box with this change?

**Comment by surakin** [comment]
> Is it necessary to keep the `Sending {spinner}` box with this change?

I understand this is the only feedback until https://github.com/matrix-org/matrix-rust-sdk/issues/1732 is sorted out

**Comment by frebib** [comment]
A small bug I noticed today: Trying to send a captioned image as a reply sends okay, but doesn't attach the reply metadata to the event and leaves the reply box in the composer

**Comment by surakin** [comment]
> A small bug I noticed today: Trying to send a captioned image as a reply sends okay, but doesn't attach the reply metadata to the event and leaves the reply box in the composer

Hmmm sending replies with anything other than text is not supported yet anyway
Maybe disabliing attachments on reply mode would be enough for now

**Comment by TGRush** [comment]
> Hmmm sending replies with anything other than text is not supported yet anyway

In what sense? I have seen many users (especially beeper users) send images in reply to messages and they get rendered in EXA just fine, is there a limitation on the Rust-SDK's end maybe? :thinking:

**Comment by frebib** [comment]
I just realised that you can't edit captions with this after I typo'd one today

**Comment by bmarty** [comment]
Thanks for the proposal. We will work very soon on this part, and it will be possible to add a caption (and do other actions on the media), in the preview screen.

**Pull request closed without merging**
