### PR TITLE
[Feature] Render m.sticker events

### LINKED ISSUE #1949: Add support for rendering `m.sticker` Event.
`{"content":{"body":"\ud83e\udd14 (thinking face)","external_url":"https://t.me/organicmaps/34029","fi.mau.telegram.source":{"chat_id":1495267990,"id":34029,"peer_type":"channel","space":1495267990},"info":{"fi.mau.telegram.sticker":{"alt":"\ud83e\udd14","id":"1067584434330402952","pack":{"access_hash":"1356583802377053769","id":"1067584434330402819"}},"h":256,"mimetype":"image/webp","size":26924,"thumbnail_info":{"fi.mau.telegram.sticker":{"alt":"\ud83e\udd14","id":"1067584434330402952","pack":{"access_hash":"1356583802377053769","id":"1067584434330402819"}},"h":256,"mimetype":"image/webp","size":26924,"w":256},"thumbnail_url":"mxc://t2bot.io/b3bd9bc62375efe07a0cb0c5ba3a51aeb0369fdf1730481839837020160","w":256},"url":"mxc://t2bot.io/b3bd9bc62375efe07a0cb0c5ba3a51aeb0369fdf1730481839837020160"},"origin_server_ts":1701413995000,"room_id":"!wqHDOeaqKhfWGKYfGs:matrix.org","sender":"@telegram_5718178991:t2bot.io","type":"m.sticker","unsigned":{},"event_id":"$jKXU4ymDyFJhbLEZ0lNpV4KPRpMLkuZfxVgN72FT5XY","user_id":"@telegram_5718178991:t2bot.io"}`

### PR DESCRIPTION
**Pull request by surakin**
Render m.sticker events

Closes #1949

 
## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Added rendering of sticker events (both the event and the reply preview)

## Motivation and context

This solves https://github.com/element-hq/element-x-android/issues/1949.
I mostly use matrix to talk via whatsapp bridges and this fixes having to switch to whatsapp just to see what sticker someone just sent.

## Screenshots / GIFs

image

## Tests

I sent myself stickers using Cinny web and Whatsapp and check them in both the emulator & my own phone

## Tested devices

- [x] Physical
- [x] Emulator
- OS version(s):
Android 13 & 14

## Checklist

- [x] Changes have been tested on an Android device or Android emulator with API 23
- [x] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#changelog
- [x] Pull request includes screenshots or videos if containing UI changes
- [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR

Signed-off-by: Marco Antonio Alvarez <surakin@gmail.com>

### CODE REVIEW

**Comment by jmartinesp** [comment]
Thanks for the contribution!

- The code seems to work quite well, although there are some minor issues with the way the sticker is displayed and the timestamp: in [this when clause](https://github.com/element-hq/element-x-android/blob/64c873922a9fe96f77540db564f7c6c1b3a578a6/features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/timeline/components/TimelineItemEventRow.kt#L584) you can see how items with media (image, video, location, etc.) are displayed in an `Overlay` mode, the same thing should be done for stickers.
- The issue with API 23 is being handled at the moment, don't worry about that check.
- Also, you'll need to create a commit with a [sign-off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off) for this to be approved and merged.

Once you mark this as ready for review I'll give it some more thorough review.

**Comment by surakin** [comment]
> * The code seems to work quite well, although there are some minor issues with the way the sticker is displayed and the timestamp: in [this when clause](https://github.com/element-hq/element-x-android/blob/64c873922a9fe96f77540db564f7c6c1b3a578a6/features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/timeline/components/TimelineItemEventRow.kt#L584) you can see how items with media (image, video, location, etc.) are displayed in an `Overlay` mode, the same thing should be done for stickers.

I'm wondering if showing the timestamp below the sticker would be better, because stickers are quite small and you can't open them, so you'll always get some of it hidden by the timestamp overlay

**Comment by bmarty** [comment]
Thanks for your contribution @surakin !

> you can't open them

Maybe a `onClick` support to view the sticker in the MediaViewer? Element Android allows this (but not Element Web).

**Comment by jmartinesp** [comment]
@surakin sorry for the bumpy process, but I think it's the actual 1st contribution to be merged in the repo and we're seeing some issues with our CI processes and forks 😓 .

Since you made some changes to the previews we now need to update the screenshots, but that's proven to be problematic if it's done locally on your PC, so we use the CI for that. However, I'm not 100% sure on how to proceed when forks are involved.

Now that https://github.com/element-hq/element-x-android/pull/2141 has been merged, could you either merge or rebase the latest changes in `develop` and run the `Record screenshots` for your branch [in your repo](https://github.com/surakin/element-x-android/actions/)? It's a bit weird because I can't see the GH action workflow displayed there, but maybe it's a permission issue.

Otherwise, maybe installing the Github CLI and using this command would generate the new screenshots in the uploaded branch:

```
gh workflow run recordScreenshots.yml --ref (git rev-parse --abbrev-ref HEAD)
```

**Comment by jmartinesp** [comment]
It worked, thanks! There are a lot of extra screenshots, but that's normal, given some issues on how Paparazzi names screenshots.

**Comment by surakin** [comment]
> I think it's the actual 1st contribution to be merged in the repo 
Am I the first? Yay me! 🥳

**Comment by jmartinesp** [comment]
@surakin it seems like the CI got stuck after the screenshots were generated and I can't approve it... Could you make some change, like a no-op commit or rebasing the existing content so it's triggered again?

**Comment by surakin** [comment]
did that help?

**Comment by jmartinesp** [comment]
> did that help?

Yes, it's running now. Thank you again!

**Comment by jmartinesp** [comment]
It seems like there are some failing tests in `:libraries:push:impl` related to the stickers, could you fix those?

**Comment by surakin** [comment]
Ups, missed that one. Fixed.

**Review by jmartinesp — APPROVED** [review]
Everything looks good now, thanks! The Maestro checks won't pass because of GH limitations of CI in forks, so I'll just skip them.

**Comment by surakin** [comment]
What about codecov? Should I worry about that? (first time I see it)

**Comment by jmartinesp** [comment]
No, it's ok. The coverage dropped a bit because a lot of code was added and only some of it could be tested, but it's no big deal. Thanks again!

**Comment by surakin** [comment]
Awesome! Happy to help :partying_face:

**Pull request merged**
