### PR TITLE
fix : protect some usages of client to avoid crashes

### PR DESCRIPTION
**Pull request by bmarty**
Fixes https://github.com/element-hq/element-x-android-rageshakes/issues/3375 and other rageshakes.

### CODE REVIEW

**Comment by ganfra** [comment]
Mmmm, this is weird, this means there is an old client still referenced?

**Comment by bmarty** [comment]
> Mmmm, this is weird, this means there is an old client still referenced?

Nothing is done to stop `SendQueues`. This is maybe another way to fix the issue?

**Comment by jmartinesp** [comment]
According to the logs, the user was signed out but the app wasn't killed, so when the app was opened again it tried re-instantiating the client given the session id saved in the navigation state, which I guess either returned a new instance or retained one of our MatrixClient wrappers and then failed when it tried using the underlying Client:

```
2024-11-16T14:01:24.646079Z ERROR elementx: [Push/Notification/DefaultNotifiableEventResolver] Unable to resolve event: ----.
java.lang.IllegalStateException: NotificationClient object has already been destroyed
	at org.matrix.rustcomponents.sdk.NotificationClient.getNotification(SourceFile:147)
	at io.element.android.libraries.matrix.impl.notification.RustNotificationService$getNotification$2.invokeSuspend(SourceFile:55)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:9)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:107)
	at com.google.android.gms.tasks.zzc.run(SourceFile:49)
	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:93)
 | 
2024-11-16T14:01:24.647532Z  WARN elementx: [Push/PushHandler] Unable to get a notification data | 
2024-11-16T14:02:31.132845Z  WARN elementx: [MainActivity] onCreate, with savedInstanceState: true | 
2024-11-16T14:02:31.158780Z  WARN elementx: [MainActivity] onNewIntent | 
2024-11-16T14:02:31.159743Z  WARN elementx: [MainActivity] onResume | 
2024-11-16T14:02:31.223778Z DEBUG elementx: Current app migration version: 7. No migration needed. | 
2024-11-16T14:02:31.240437Z  WARN elementx: [MainActivity] onMainNodeInit | 
2024-11-16T14:02:31.241957Z DEBUG elementx: Restore state | 
2024-11-16T14:02:31.242295Z  WARN elementx: Restore with non-empty map | 
2024-11-16T14:02:31.242762Z DEBUG elementx: [Lifecycle] onCreate RootFlowNode | 
2024-11-16T14:02:31.246803Z DEBUG elementx: [Lifecycle] onCreate LoggedInFlowNode | 
2024-11-16T14:02:31.247212Z DEBUG elementx: [Navigation] Navigating to session @patricka:element.io. Current state: Root | 
2024-11-16T14:02:31.247596Z DEBUG elementx: [Navigation] Navigating to space !mainSpace:local. Current state: Session(owner=---, sessionId=---) | 
2024-11-16T14:02:31.248198Z DEBUG elementx: [Lifecycle] onCreate LoggedInAppScopeFlowNode | 
2024-11-16T14:02:31.248975Z DEBUG elementx: Navigating to Room(sessionId=---, roomId=---, threadId=null) | 
2024-11-16T14:02:31.252992Z DEBUG elementx: [Lifecycle] onCreate RoomListNode | 
2024-11-16T14:02:31.253392Z  INFO elementx: setAllSendQueuesEnabled(true) | 
2024-11-16T14:02:31.253413Z DEBUG elementx: [Lifecycle] onCreate LoggedInNode | 
2024-11-16T14:02:31.255261Z DEBUG elementx: [Lifecycle] onCreate RoomFlowNode | 
2024-11-16T14:02:31.256300Z DEBUG elementx: [Lifecycle] onCreate ComposableNode | 
2024-11-16T14:02:31.257910Z DEBUG elementx: Room membership: JOINED | 
2024-11-16T14:02:31.259225Z DEBUG elementx: [Lifecycle] onCreate JoinedRoomFlowNode | 
2024-11-16T14:02:31.260418Z DEBUG elementx: [Lifecycle] onCreate ComposableNode | 
2024-11-16T14:02:31.261355Z DEBUG elementx: Room factory is destroyed, returning null for --- | 
2024-11-16T14:02:31.262613Z DEBUG elementx: Save matrix session keys = [---] | 
2024-11-16T14:02:32.749333Z TRACE elementx: Uncaught exception: java.lang.IllegalStateException: Client object has already been destroyed | 
```

**Comment by ganfra** [comment]
So there is probably a scenario where `MatrixClientsHolder` is not updated correctly

**Comment by ganfra** [comment]
I've made more investigations on this, and there are some conditions where, while replacing the `LoggedInFlowNode`, we can get several calls to a destroyed `client`, the time the node get removed from the composition.

So we have 2 choices : 
- either we protect every call to the rust client with try/catch
- either we remove the call to `client.destroy` and let the GC release the memory when needed

This crash has also emphasised another issue with the refresh token, we need more logs (https://github.com/matrix-org/matrix-rust-sdk/pull/4301)

**Review by ganfra — APPROVED** [review]
I made some more changes, let me know!

**Review by bmarty — COMMENTED** [review]
Approved!

**Pull request merged**
