### PR TITLE
Don't delete uploaded logs

### PR DESCRIPTION
**Pull request by jmartinesp**
## Content

Remove code in `DefaultBugReporter` that deleted all existing log files except for the most recent one. 

## Motivation and context

The log removal happened after the logs had been compressed but before we were sure they had reached their destination. Since Rust already takes care of the log roration there's no need for this code AFAICT, and it could cause accidental log data loss.

## Tests

- Send a bug report.
- Send another or check the files in your device with `adb`.

The log files should be kept.

## Tested devices

- [x] Physical
- [ ] Emulator
- OS version(s): 14

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 23
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request title will be used in the release note, it clearly define what will change for the user
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR

### CODE REVIEW

**Comment by ganfra** [comment]
Are you sure rust sdk is cleaning them? At the time I implemented that it wasn't the case

**Comment by jmartinesp** [comment]
> Are you sure rust sdk is cleaning them? At the time I implemented that it wasn't the case

It should be, we're internally using this:

image

Also, that was over a year ago, I think 😅 .

**Comment by ganfra** [comment]
Nice, what "n" are we using?

**Comment by jmartinesp** [comment]
> Nice, what "n" are we using?

```
// Keep a maximum of 1 week of log files.
numberOfFiles = 7 * 24,
```

In any case, I'm testing this right now. But since new files are only written when every hour, I need to wait for a bit 🫠 .

**Review by ganfra — APPROVED** [review]

**Comment by jmartinesp** [comment]
> In any case, I'm testing this right now.

Well, color me surprised, it doesn't, or not under some circumstances: I lowered the max value to 2 and I have still all my logs here.

**Comment by bmarty** [comment]
(We hold on until we are sure that the SDK is deleting the files during the rotation).

**Comment by jmartinesp** [comment]
https://github.com/matrix-org/matrix-rust-sdk/pull/4038 is now merged, we'd need a new SDK version and we can both fix the bud and remove this code.

**Comment by jmartinesp** [comment]
We now have the right log rotation code since https://github.com/element-hq/element-x-android/pull/3553.

**Review by bmarty — APPROVED** [review]

**Pull request merged**
