### PR TITLE
Clarify model for Event with attachment

### PR DESCRIPTION
**Pull request by bmarty**
## Content

Clarify model for Event with attachment. They must have a `filename: String` and they may have a `body :String?` (caption).

If filename is missing from the SDK model, the body is used instead and in this case the body is not mapped to our model.

## Motivation and context

Cleanup following change in #3567 
The changes here should reduce the risk of errors.

## Tests

- Should not have any impact.

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s):

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 23
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request title will be used in the release note, it clearly define what will change for the user
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR

### CODE REVIEW

**Review by ganfra — COMMENTED** [review]
I think this is the opposite, from reading the spec? 


`body | string | Required: If filename is not set or the value of both properties are identical, this is the filename of the original upload. Otherwise, this is a caption for the image.Changed in v1.10: This property can act as a caption for the image.`


`filename | string | The original filename of the uploaded file.Added in v1.10
`

The body is mandatory but the filename is not

**Comment by bmarty** [comment]
We are just mapping what the SDK is providing to the application here. There is maybe a problem in the SDK then?

**Comment by ganfra** [comment]
> We are just mapping what the SDK is providing to the application here. There is maybe a problem in the SDK then?

Mmm AFAICT, the SDK returns a non-nullable body and a nullable filename?

**Comment by bmarty** [comment]
Yes, I have read it too fast, my bad

The mapping I have done [in the EventContentMapper](https://github.com/element-hq/element-x-android/pull/3574/files#diff-9b8993ef173a404ecbf23a0c01d42502c4e95379978611aa95c3e9fc7785b0a5R53-R54) is still correct to me, and the application needs a non-nullable filename.

So we always have a `filename`, which may be from the `body` and we have an optional `body` which is actually either the `filename`, or the `caption`. Do you see a problem with this approach?

**Comment by ganfra** [comment]
I think we should keep the mapping as they come from sdk, otherwise it brings confusion.
I'd instead offer some methods to get the correct value (or computed val),
like `computedFilename()` and `computedCaption()`

**Comment by bmarty** [comment]
OK, let's wait for the SDK to change, I think this is discussed in #2570.

**Comment by pixlwave** [comment]
Heads up that this is now available in the SDK: https://github.com/matrix-org/matrix-rust-sdk/pull/4081

`mediaTimelineItem.filename` will always be the filename and `mediaTimelineItem.caption`/`formattedCaption` will only exist when there's a caption to show.

**Comment by bmarty** [comment]
@ganfra PR updated with what is provided in https://github.com/matrix-org/matrix-rust-sdk/pull/4081

**Comment by bmarty** [comment]
@ganfra do you love the update of this PR?

**Pull request merged**
