### PR TITLE
Remove Welcome screen from the FTUE

### LINKED ISSUE #2584: [Task] FTUE - Remove the welcome screen
Please see and discuss the details in the meta issue.

### PR DESCRIPTION
**Pull request by jmartinesp**
## Type of change

- [ ] Feature
- [ ] Bugfix
- [ ] Technical
- [x] Other : UI flow changes

## Content

- Remove `WelcomeScreen` from the FTUE flow.

## Motivation and context

Closes #2584.

## Screenshots / GIFs

A few screenshots should have been removed.

## Tests

- Log into the app.

The welcome screen, which should appear as the first step in the FTUE flow, should be gone. You should see the notification permission screen instead in API >= 33 or the analytics one in API < 33.

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s): 12, 13.

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 23
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [x] Pull request is based on the develop branch
- [x] Pull request includes a new file under ./changelog.d. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#changelog
- [x] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [x] You've made a self review of your PR

### CODE REVIEW

**Comment by jmartinesp** [comment]
I just re-uploaded the branch because it seems like we want to keep the logic and UI of the welcome screen around in case we want to reuse it in the future.

**Review by bmarty — COMMENTED** [review]
If we want to keep the screen around, can we limit the change to add a feature flag that will be used only in `isWelcomeScreenNeeded()`?

**Comment by jmartinesp** [comment]
We're going to replace the screen with the verify session one, so I'd rather not add the FF and make the flow more complex than it needs to be. If we do add it again later it might not even be as the first step of the flow.

**Review by bmarty — APPROVED** [review]
OK, thanks.

**Pull request merged**
