### PR TITLE
Add support for sending images from the keyboard

### LINKED ISSUE #1977: Be able to send image from keyboard
When trying to send an image from the keyboard, the app is displaying an error:

image

The image should be sent as a regular image, as it was the case for EA. It will probably require some changes on the the rich text editor library.

For reference, this is the EA implementation for the RTE: https://github.com/vector-im/element-android/pull/8185

### PR DESCRIPTION
**Pull request by bmarty**
## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Add ability to send media from the keyboard

Need https://github.com/matrix-org/matrix-rich-text-editor/pull/915

## Motivation and context

Better integration with the major Android keyboards, and parity with EA.
Closes #1977 

## Screenshots / GIFs

SendImageFromKb

## Tests

- Open a room with permission to send message
- From the keyboard, select an image
- observe that the image is sent to the room

## Tested devices

- [ ] Physical
- [x] Emulator
- OS version(s):

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 23
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR

### CODE REVIEW

**Review by jmartinesp — APPROVED** [review]
I tested this on several devices and it worked just fine on all but one, but I've also seen other weird issues in it, so it might be an OS issue.

Worst case scenario: we'll need to re-visit this feature in the feature to find what's wrong with that specific device.

**Comment by jmartinesp** [comment]
Btw, I tested this again with another device and it also worked as expected, so I have no idea what's the problem with the one I used for testing before. I guess we can merge this if the CI passes?

**Comment by bmarty** [comment]
Using the device with the issue @jmartinesp does it work correctly with EA (with RTE disabled), or with other messaging apps or anything else supporting sending image from KB?

**Comment by jmartinesp** [comment]
> Using the device with the issue @jmartinesp does it work correctly with EA (with RTE disabled), or with other messaging apps or anything else supporting sending image from KB?

In EA it works with the RTE disabled, it also works in Telegram or the SMS app 😞 .

**Comment by jmartinesp** [comment]
I actually got it working! We need to override `commitContent` to return `true` in the `InterceptInputConnection`  class in the RTE editor, and possible add some extra config in `onCreateInputConnection`. I'll check the details tomorrow.

**Comment by jmartinesp** [comment]
> I actually got it working! We need to override `commitContent` to return `true` in the `InterceptInputConnection` class in the RTE editor (I guess depending on the API version it returns `true` or `false` by default), ~and possibly add some extra config in `onCreateInputConnection`~. I'll check the details tomorrow.

Added a fix here: https://github.com/matrix-org/matrix-rich-text-editor/pull/919

**Comment by bmarty** [comment]
(Updated the branch to get the latest version of the RTE lib)

**Pull request merged**
