### PR TITLE
Fix localazy sync

### PR DESCRIPTION
**Pull request by bmarty**
Those changes should fix all the problems identified here: https://github.com/element-hq/element-x-android/pull/2465#issuecomment-1970638968

### CODE REVIEW

**Comment by jmartinesp** [comment]
Can we launch the flow on this branch so we check if these changes do fix the issues?

**Comment by bmarty** [comment]
> Can we launch the flow on this branch so we check if these changes do fix the issues?

I do not think it will work (I already tried on the other PR), since the localazy workflow is creating a PR, it's not committing on the branch.

**Comment by bmarty** [comment]
Note: I have tested the script locally and the issue with the xml formatter is fixed.

**Review by jmartinesp — APPROVED** [review]
Ok, let's check if it works then.

**Comment by bmarty** [comment]
https://github.com/element-hq/element-x-android/actions/runs/8094108848

**Pull request merged**
