### PR TITLE
Ensure that a PushProvider is available on a device before using it.

### PR DESCRIPTION
**Pull request by bmarty**
## Type of change

- [x] Feature
- [ ] Bugfix
- [ ] Technical
- [ ] Other :

## Content

Ensure that a PushProvider is available on a device before using it.
It help to fallback to UnifiedPush (if available) if the PlayServices are not installed on the device.

## Motivation and context

Let the device fallback to UnifiedPush if the PlayServices is not available on the device, even if installed from the PlayStore.

## Tests

- Step 1
- Step 2
- Step ...

## Tested devices

- [ ] Physical
- [ ] Emulator
- OS version(s):

## Checklist

- [ ] Changes have been tested on an Android device or Android emulator with API 23
- [ ] UI change has been tested on both light and dark themes
- [ ] Accessibility has been taken into account. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#accessibility
- [ ] Pull request is based on the develop branch
- [ ] Pull request includes a new file under ./changelog.d. See https://github.com/element-hq/element-x-android/blob/develop/CONTRIBUTING.md#changelog
- [ ] Pull request includes screenshots or videos if containing UI changes
- [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
- [ ] You've made a self review of your PR

### CODE REVIEW

**Review by jmartinesp — APPROVED** [review]
The PR LGTM, thanks.

> Let the device fallback to UnifiedPush if the PlayServices is not available on the device, even if installed from the PlayStore.

Just curious, is that even possible?

**Comment by spaetz** [comment]
> Just curious, is that even possible?

Absolutely. For one thing, there are alternative store applications (eg Aurora store) which install apks from the play store without having any Google Framework installed.
Alternatively, one can enable all Play stuff, install whatever one needs and deactivate all play stuff subsequently.

...or so I have heard from a friend 😜

**Comment by K4LCIFER** [comment]
> Let the device fallback to UnifiedPush if the PlayServices is not available on the device, even if installed from the PlayStore.

Does this mean that one cannot choose to use UnifiedPush from within the app? One can only use UnifiedPush if, somehow, PlayServices is made unavailable?

**Comment by bmarty** [comment]
> Does this mean that one cannot choose to use UnifiedPush from within the app? One can only use UnifiedPush if, somehow, PlayServices is made unavailable?

Yes. There is no in app selector if both providers are available.
I you want to ensure that UnifiedPush is used, a solution could be to install the application from F-Droid when it will be available.

**Comment by K4LCIFER** [comment]
> Yes. There is no in app selector if both providers are available.

Is there a plan to add one in the future?

**Pull request merged**
