### PR TITLE
Bug: rememberSaveable on timeline items behaves erratically

### PR DESCRIPTION
**Pull request by julioromano**
Reproduce steps:
Launch the app go to a room with many voice messages. Click play on some of them, it will increase the counters displayed within the voice message. Scroll the timeline untile the voice messages go out of view. You will see that the 2 digits (the saved and not saved reset at different times but eventually both of them reset).

### CODE REVIEW

**Comment by ganfra** [comment]
> Reproduce steps: Launch the app go to a room with many voice messages. Click play on some of them, it will increase the counters displayed within the voice message. Scroll the timeline untile the voice messages go out of view. You will see that the 2 digits (the saved and not saved reset at different times but eventually both of them reset).

This is occurring because you don't give a key to `rememberSaveable`. In a regular usage, it wouldn't be a problem, but not within `LazyColumn`, see the doc : 
```
* @param key An optional key to be used as a key for the saved value. If not provided we use the
 * automatically generated by the Compose runtime which is unique for the every exact code location
 * in the composition tree
```

**Comment by julioromano** [comment]
> > Reproduce steps: Launch the app go to a room with many voice messages. Click play on some of them, it will increase the counters displayed within the voice message. Scroll the timeline untile the voice messages go out of view. You will see that the 2 digits (the saved and not saved reset at different times but eventually both of them reset).
> 
> This is occurring because you don't give a key to `rememberSaveable`. In a regular usage, it wouldn't be a problem, but not within `LazyColumn`, see the doc :
> 
> ```
> * @param key An optional key to be used as a key for the saved value. If not provided we use the
>  * automatically generated by the Compose runtime which is unique for the every exact code location
>  * in the composition tree
> ```

Though this doesn't happen in a sample compose project with the following code:

```

@Composable
fun MyUi() {
    LazyColumn(modifier = Modifier.fillMaxSize()) {
        items(1000) {
            val presenter = MyPresenter()
            MyItem(
                id = it,
                state = presenter.present(),
            )
        }
    }
}

@Composable
fun MyItem(
    id: Int,
    state: MyState,
) {
    ListItem(
        headlineContent = { Text("Counter at: ${state.number}") },
        overlineContent = { Text("Item $id") },
        supportingContent = { Text("A lot of lorem ipsum") },
        leadingContent = { Icon(Icons.Default.AccountCircle, contentDescription = null) },
        trailingContent = {
            IconButton(onClick = { state.eventSink(MyEvents.Increment) }) {
                Icon(Icons.Default.Add, contentDescription = null)
            }
        },
    )
}

data class MyState(
    val number: Int,
    val eventSink: (MyEvents) -> Unit = {},
)

sealed interface MyEvents {
    data object Increment : MyEvents
}

class MyPresenter {
    @Composable
    fun present(): MyState {
        var number by remember { mutableIntStateOf(0) }
        return MyState(
            number = number,
            eventSink = { event ->
                when (event) {
                    MyEvents.Increment -> number++
                }
            },
        )
    }
}
```

**Comment by ganfra** [comment]
You're right, I I didn't test well, it doesn't change anything with the key.
I finally found the culprit after lots of digging : at some point in the item composition we have a `SubcomposeLayout`, and it looks like it's not playing nicely with `LazyColumn`. In your sample if you add a `BoxWithConstraints` (which do use `SubcomposeLayout` internally) on top of the `ListItem`, it will behave the same than EAX... not sure what we can do :/

**Comment by julioromano** [comment]
> You're right, I I didn't test well, it doesn't change anything with the key. I finally found the culprit after lots of digging : at some point in the item composition we have a `SubcomposeLayout`, and it looks like it's not playing nicely with `LazyColumn`. In your sample if you add a `BoxWithConstraints` (which do use `SubcomposeLayout` internally) on top of the `ListItem`, it will behave the same than EAX... not sure what we can do :/

Couldn't repro. Can you past the code?

**Comment by julioromano** [comment]
> You need the `present()` method to be called inside the `BoxWithConstraints` :
> 
> ```
>  @Composable
>     fun MyUi() {
>         LazyColumn(modifier = Modifier.fillMaxSize()) {
>             items(1000) {
>                 val presenter = MyPresenter()
>                 BoxWithConstraints {
>                     maxHeight
>                     ComplexItem(id = it, state = presenter.present())
>                 }
>             }
>         }
>     }
> ```

Still can't repro, code:

```
import androidx.compose.foundation.layout.BoxWithConstraints
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.AccountCircle
import androidx.compose.material.icons.filled.Add
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.ListItem
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.tooling.preview.Preview

@Composable
fun MyUi() {
    LazyColumn(modifier = Modifier.fillMaxSize()) {
        items(1000) {
            val presenter = MyPresenter()
            BoxWithConstraints {
                maxHeight // not sure why you wrote this but I put it there since you did
                MyItem(
                    id = it,
                    state = presenter.present(),
                )
            }
        }
    }
}

@Composable
fun MyItem(
    id: Int,
    state: MyState,
) {
    ListItem(
        headlineContent = { Text("Counter at: ${state.number}") },
        overlineContent = { Text("Item $id") },
        supportingContent = { Text("A lot of lorem ipsum") },
        leadingContent = { Icon(Icons.Default.AccountCircle, contentDescription = null) },
        trailingContent = {
            IconButton(onClick = { state.eventSink(MyEvents.Increment) }) {
                Icon(Icons.Default.Add, contentDescription = null)
            }
        },
    )
}

data class MyState(
    val number: Int,
    val eventSink: (MyEvents) -> Unit = {},
)

sealed interface MyEvents {
    data object Increment : MyEvents
}

class MyPresenter {
    @Composable
    fun present(): MyState {
        var number by rememberSaveable { mutableIntStateOf(0) }
        return MyState(
            number = number,
            eventSink = { event ->
                when (event) {
                    MyEvents.Increment -> number++
                }
            },
        )
    }
}

@Preview
@Composable
fun PreviewMyUi() {
    MyUi()
}
```

**Comment by ganfra** [comment]
Nothing to do on this for now, closing.

**Pull request closed without merging**
